#!/bin/bash
# 2023_02_17_17_51_21

limpaemotes(){
#Limpa emotes
#verifica se o arquivo existe
if [[ -f "$arquivo" ]]; then
while
read -r A B;
do
sed -i "s/${A}/${B}/g" "$arquivo";
done<<EOF
:1st_place_medal: 🥇
:aerial_tramway: 🚡
:alarm_clock: ⏰
:alien: 👽
:alien_monster: 👾
:ambulance: 🚑
:american_football: 🏈
:anger_symbol: 💢
:angry: 😠
:angry_face: 😠
:angry_face_with_horns: 👿
:ant: 🐜
:antenna_bars: 📶
:anxious_face_with_sweat: 😰
:apple: 🍎
:arrow_right: ➡️
:articulated_lorry: 🚛
:artist_palette: 🎨
:astonished: 😲
:astonished_face: 😲
:astronomical_symbol_for_uranus: ⛢
:atm_sign: 🏧
:automobile: 🚗
:baby: 👶
:baby_angel: 👼
:baby_bottle: 🍼
:baby_chick: 🐤
:baby_symbol: 🚼
:back_arrow: 🔙
:backhand_index_pointing_down: 👇
:backhand_index_pointing_left: 👈
:backhand_index_pointing_right: 👉
:backhand_index_pointing_up: 👆
:backpack: 🎒
:bacon: 🥓
:baggage_claim: 🛄
:balance_scale: ⚖
:balloon: 🎈
:banana: 🍌
:bangbang: ✖
:bank: 🏦
:barber_pole: 💈
:bar_chart: 📊
:basketball: 🏀
:bathtub: 🛁
:battery: 🔋
:b_button_(blood_type): 🅱️
:beach_with_umbrella: 🏖️
:beaming_face_with_smiling_eyes: 😁
:bear: 🐻
:beating_heart: 💓
:bee: 🐝
:beer: 🍺
:beer_mug: 🍺
:bell: 🔔
:bell_with_slash: 🔕
:bento_box: 🍱
:beverage_box: ✖️
:bicycle: 🚲
:bikini: 👙
:bird: 🐦
:birthday_cake: 🎂
:bison: 🐂
:black_square_button: 🔲
:blossom: 🌼
:blowfish: 🐡
:blue_book: 📘
:blue_circle: 🔵
:blue_heart: 💙
:blush: 😳
:boar: 🐗
:body-blue-raised-arms: 🙋‍♂️
:bomb: 💣
:bookmark: 🔖
:bookmark_tabs: 📑
:books: 📚
:boom: 💥
:bouquet: 💐
:bowling: 🎳
:boxing_glove: 🥊
:boy: 👦
:brain: 🧠
:bread: 🍞
:bridge_at_night: 🌉
:briefcase: 💼
:bright_button: 🔆
:broken_heart: 💔
:broom: ✖
:buffering: ⌛
:bug: 🐛
:bulb: 💡
:bullet_train: 🚅
:bullseye: 🎯
:bus: 🚌
:bus_stop: 🚏
:bust_in_silhouette: 👤
:busts_in_silhouette: 👥
:cactus: 🌵
:cake: 🎂
:calendar: 📅
:call_me_hand: 🤙
:camel: 🐪
:camera: 📷
:camera_with_flash: 📸
:candle: 🕯️
:candy: 🍬
:card_index: 📇
:carousel_horse: 🎠
:carpentry_saw: ✖️
:carp_streamer: 🎏
:castle: 🏰
:cat: 🐈
:cat_face: 🐱
:cat_with_tears_of_joy: 😹
:cat_with_wry_smile: 😼
:chart_decreasing: 📉
:chart_increasing: 📈
:chart_increasing_with_yen: 💹
:chart_with_downwards_trend: 📉
:check_mark_button: ✅
:cheese_wedge: 🧀
:chequered_flag: 🏁
:cherries: 🍒
:cherry_blossom: 🌸
:chestnut: 🌰
:chicken: 🐔
:children_crossing: 🚸
:chillwcat: ✖
:chocolate_bar: 🍫
:christmas_tree: 🎄
:cigarette: 🚬
:cinema: 🎦
:circus_tent: 🎪
:cityscape_at_dusk: 🌆
:clap: 👏
:clapper: 🎬
:clapper_board: 🎬
:clapping_hands: 👏
:cl_button: 🆑
:clinking_beer_mugs: 🍻
:clinking_glasses: 🍻
:clipboard: 📋
:clockwise_vertical_arrows: 🔃
:closed_book: 📕
:closed_mailbox_with_lowered_flag: 📪
:closed_mailbox_with_raised_flag: 📫
:closed_umbrella: 🌂
:clown_face: 🤡
:clutch_bag: 👝
:cocktail_glass: 🍸
:coffee: ☕
:coffin: ⚰
:cold_face: ✖️
:collision: 💥
:computer_disk: 💽
:confetti_ball: 🎊
:confounded: 😖
:confounded_face: 😖
:confused: 😕
:confused_face: 😕
:construction: 🚧
:construction_worker: 👷
:convenience_store: 🏪
:cooked_rice: 🍚
:cookie: 🍪
:cooking: 🍳
:cool_button: 🆒
:corn: 🌽
:counterclockwise_arrows_button: 🔄
:couple_with_heart: 💑
:cow: 🐄
:cow_face: 🐮
:crab: 🦀
:credit_card: 💳
:crescent_moon: 🌙
:cricket: 🦗️
:crocodile: 🐊
:crossed_flags: 🎌
:cross_mark: ❌
:cross_mark_button: ❎
:crown: 👑
:crying_cat: 😿
:crying_face: 😢
:crystal_ball: 🔮
:cucumber: 🥒
:cupid: 💘
:curly_loop: ➰
:currency_exchange: 💱
:curry_rice: 🍛
:custard: 🍮
:customs: 🛃
:cut_of_meat: 🥩
:cyclone: 🌀
:dancer: 💃
:dango: 🍡
:dark_sunglasses: 🕶️
:dart: 🎯
:dash: ✖️
:dashing_away: 💨
:deciduous_tree: 🌳
:delivery_truck: 🚚
:department_store: 🏬
:diamond_with_a_dot: 💠
:dim_button: 🔅
:disappointed: 😞
:disappointed_face: 😞
:disappointed_relieved: 😵‍💫
:disguised_face: ✖️
:divide: ➗
:dizzy: 💫
:dog: 🐕
:dog2: 🐕
:dog_face: 🐶
:dollar: 💵
:dollar_banknote: 💵
:dolphin: 🐬
:door: 🚪
:dothefive: 5️⃣
:dotted_six-pointed_star: 🔯
:double_curly_loop: ➿
:double_exclamation_mark: ‼
:doughnut: 🍩
:dove: 🕊️
:dove_of_peace: 🕊️
:downcast_face_with_sweat: 😓
:downwards_button: 🔽
:dragon: 🐉
:dragon_face: 🐲
:dress: 👗
:drooling_face: 🤤
:droplet: 💧
:duck: 🦆
:dvd: 📀
:ear: 👂
:ear_of_corn: 🌽
:ear_of_rice: 🌾
:earth_africa: 🌍
:earth_americas: 🌎
:earth_asia: 🌏
:egg: 🥚
:egg2: 🥚
:eggplant: 🍆
:eight_oclock: 🕗
:eight-thirty: 🕣
:elbowcough: 💪
:electric_plug: 🔌
:elephant: 🐘
:eleven_oclock: 🕚
:eleven-thirty: 🕦
:e-mail: 📧
:end_arrow: 🔚
:enraged_face: 😡
:envelope_with_arrow: 📩
:euro_banknote: 💶
:evergreen_tree: 🌲
:ewe: 🐑
:exclamation_question_mark: ⁉
:exploding_head: 🤯
:expressionless: 😑
:expressionless_face: 😑
:eye: 👁
:eye_in_speech_bubble: 👁️‍🗨️
:eyes: 👀
:eyes-pink-heart-shape: 😍
:face_blowing_a_kiss: 😘
:face-blue-smiling: 😍
:face-fuchsia-poop-shape: ✖
:face-fuchsia-wide-eyes: ✖
:face-orange-raised-eyebrow: ✖
:facepunch: 👊
:face-purple-crying: 😢
:face-purple-smiling-fangs: ✖
:face-purple-smiling-tears: ✖
:face-purple-wide-eyes: ✖
:face_savoring_food: 😋
:face_screaming_in_fear: 😱
:face-turquoise-covering-eyes: ✖
:face-turquoise-drinking-coffee: ✖
:face_vomiting: 🤮
:face_with_crossed-out_eyes: 😵
:face_with_hand_over_mouth: 🤭
:face_with_head_bandage: 🤕
:face_with_medical_mask: 😷
:face_with_monocle: 🧐
:face_with_open_mouth: 😮
:face_without_mouth: 😶
:face_with_raised_eyebrow: 🤨
:face_with_rolling_eyes: 🙄
:face_with_spiral_eyes: 😵‍💫
:face_with_steam_from_nose: 😤
:face_with_symbols_on_mouth: 🤬
:face_with_tears_of_joy: 😂
:face_with_tongue: 😛
:factory: 🏭
:fallen_leaf: 🍂
:family: 👪
:fast_down_button: ⏬
:fast-forward_button: ⏩
:fast_reverse_button: ⏪
:fast_up_button: ⏫
:fax_machine: 📠
:fearful_face: 😨
:ferris_wheel: 🎡
:file_folder: 📁
:fire: 🔥
:firecracker: 💣
:fire_engine: 🚒
:fireworks: 🎆
:first_quarter_moon: ☽
:first_quarter_moon_face: 🌛
:first_quarter_moon_with_face: 🌛
:fish: 🐟
:fish_cake_with_swirl: 🍥
:fishing_pole: 🎣
:fist: ✊
:five_oclock: 🕔
:five-thirty: 🕠
:flag_in_hole: ⛳
:flashlight: 🔦
:flexed_biceps: 💪
:flipper: 🐬
:floppy_disk: 💾
:flower_playing_cards: 🎴
:flushed: 😳
:flushed_face: 😳
:fly: ✖
:flying_saucer: 🛸
:foggy: 🌁
:folded_hands: 🙏
:footprints: 👣
:fork_and_knife: 🍴
:four_leaf_clover: 🍀
:four_oclock: 🕓
:four-thirty: 🕟
:free_button: 🆓
:french_fries: 🍟
:fried_shrimp: 🍤
:frog: 🐸
:front-facing_baby_chick: 🐥
:fuel_pump: ⛽
:fuelpump: ⛽
:full_moon: 🌕
:full_moon_face: 🌝
:full_moon_with_face: 🌝
:game_die: 🎲
:garlic: ✖️
:gem_stone: 💎
:ghost: 👻
:gift: 🎁
:girl: 👧
:glasses: 👓
:glass_of_milk: 🥛
:globe_showing_americas: 🌎
:globe_showing_asia-australia: 🌏
:globe_showing_asia_australia: 🌏
:globe_showing_europe-africa: 🌍
:globe_showing_europe_africa: 🌍
:globe_with_meridians: 🌐
:glowing_star: 🌟
:goat: 🐐
:goat-turquoise-white-horns: ✖
:goblin: 👺
:golf: 🏌️‍
:goodvibes: ✌️
:graduation_cap: 🎓
:grapes: 🍇
:green_apple: 🍏
:green_book: 📗
:green_heart: 💚
:grimacing: 😬
:grimacing_face: 😬
:grin: 😀
:grinning: 😀
:grinning_cat: 😺
:grinning_cat_with_smiling_eyes: 😸
:grinning_face: 😀
:grinning_face_with_big_eyes: 😃
:grinning_face_with_smiling_eyes: 😁
:grinning_face_with_sweat: 😅
:grinning_squinting_face: 😆
:growing_heart: 💗
:guard: 💂
:guitar: 🎸
:hamburger: 🍔
:hammer: 🔨
:hammer_and_wrench: 🛠️
:hamster: 🐹
:handbag: 👜
:hand-orange-covering-eyes: ✖
:hand-pink-waving: ✖
:hand-purple-blue-peace: ✖
:handshake: 🤝
:hand_with_fingers_splayed: 🖐
:hankey: ✖
:hatching_chick: 🐣
:headphone: 🎧
:hear_no_evil: 🙉
:hear-no-evil_monkey: 🙉
:hear_no_evil_monkey: 🙉
:heart: ❤
:heart_decoration: 💟
:heart_exclamation: ❣️
:heart_eyes: 😍
:heart_on_fire: ❤‍🔥
:heartpulse: 💝
:hearts: 💝
:heart_suit: ♥️
:heart_with_arrow: 💘
:heart_with_ribbon: 💝
:heavy_dollar_sign: 💲
:heavy_heart_exclamation_mark_ornament: ❣️
:helicopter: 🚁
:herb: 🌿
:hibiscus: 🌺
:high-heeled_shoe: 👠
:high-speed_train: 🚄
:high_voltage: ⚡
:hocho: 🔪
:honeybee: 🐝
:honey_pot: 🍯
:horizontal_traffic_light: 🚥
:horse: 🐎
:horse_face: 🐴
:horse_racing: 🏇
:hospital: 🏥
:hot_beverage: ☕
:hotel: 🏨
:hot_face: ✖
:hourglass_done: ✖
:hourglass_not_done: ⏳
:house: 🏠
:house_with_garden: 🏡
:hugging_face: 🤗
:hundred_points: 💯
:hushed_face: 😯
:hydrate: ✖
:ice_cream: 🍨
:id_button: 🆔
:imp: ✖
:inbox_tray: 📥
:incoming_envelope: 📨
:index_pointing_up: ☝️
:input_latin_letters: 🔤
:input_latin_lowercase: 🔡
:input_latin_uppercase: 🔠
:input_numbers: 🔢
:input_symbols: 🔣
:interrobang: ⁉️
:inverted_pentagram: ⛧
:jack-o-lantern: 🎃
:japanese_castle: 🏯
:japanese_dolls: 🎎
:japanese_ogre: 👹
:japanese_post_office: 🏣
:japanese_symbol_for_beginner: 🔰
:jeans: 👖
:joker: 🃏
:joy: 😂
:key: 🔑
:keycap:_10: 🔟
:kimono: 👘
:kiss: 💋
:kissing_cat: 😽
:kissing_face: ✖
:kissing_face_with_closed_eyes: 😚
:kissing_face_with_smiling_eyes: 💋
:kissing_heart: 😘
:kissing_smiling_eyes: 💋
:kiss_mark: 💋
:kitchen_knife: 🔪
:knife: 🔪
:knocked_out_face: 😵
:koala: 🐨
:lady_beetle: 🐞
:laptop: 💻
:large_blue_diamond: 🔷
:large_orange_diamond: 🔶
:last_quarter_moon: ☾
:last_quarter_moon_face: 🌜
:last_quarter_moon_with_face: 🌜
:last_track_button: ⏮️
:laughing: 🤣
:leaf_fluttering_in_wind: 🍃
:ledger: 📒
:left_facing_fist: 🤛
:left-handed_interlaced_pentagram: ⛦
:left_luggage: 🛅
:lemon: 🍋
:leopard: 🐆
:light_bulb: 💡
:light_rail: 🚈
:link: 🔗
:lips: 💋
:lipstick: 💄
:litter_in_bin_sign: 🚮
:locked: 🔒
:locked_with_key: 🔐
:locked_with_pen: 🔏
:locomotive: 🚂
:lollipop: 🍭
:loudly_crying_face: 😭
:loud_sound: 🔊
:loudspeaker: 📢
:love_hotel: 🏩
:love_letter: 💌
:love_you_gesture: ✖
:lying_face: 🤥
:magnet: ✖
:magnifying_glass_tilted_left: 🔍
:magnifying_glass_tilted_right: 🔎
:mag_right: ✖
:man: 👨
:man_facepalming: 🤦‍♂
:man_fairy: 👨
:man_shrugging: 🤷‍♂
:mans_shoe: 👞
:man_surfing: 🏄‍♂️
:man_swimming: 🏊‍♂
:man_zombie: 🧟‍♂
:maple_leaf: 🍁
:map_of_japan: 🗾
:martial_arts_uniform: 🥋
:meat_on_bone: 🍖
:mechanical_arm: ✖
:megaphone: 📣
:melon: 🍈
:memo: 📝
:men_holding_hands: 👬
:mens_room: 🚹
:metro: 🚇
:microphone: 🎤
:microscope: 🔬
:middle_finger: 🖕
:military_medal: ✖
:milky_way: 🌌
:minibus: 🚐
:minus: ➖
:moai: 🗿
:mobile_phone: 📱
:mobile_phone_off: 📴
:mobile_phone_with_arrow: 📲
:money_bag: 💰
:moneybag: 💰
:money_mouth_face: 🤑
:money_with_wings: 💸
:monkey: 🐒
:monkey_face: 🐵
:monorail: 🚝
:moon: 🌕
:moon_viewing_ceremony: 🎑
:motor_boat: 🛥️
:motor_scooter: 🛵
:mountain_cableway: 🚠
:mountain_railway: 🚞
:mount_fuji: 🗻
:mouse: 🐁
:mouse_face: 🐭
:mouth: 👄
:movie_camera: 🎥
:moyai: 🗿
:multiply: ✖️
:muscle: 💪
:mushroom: 🍄
:musical_keyboard: 🎹
:musical_note: 🎵
:musical_notes: 🎶
:musical_score: 🎼
:mute: 🔇
:muted_speaker: 🔇
:nail_care: 💅
:nail_polish: 💅
:name_badge: 📛
:national_park: 🏞
:nauseated_face: 🤢
:necktie: 👔
:nerd_face: 🤓
:neutral_face: 😐
:new_button: 🆕
:new_moon: 🌑
:new_moon_face: 🌚
:new_moon_with_face: 🌚
:newspaper: 📰
:next_track_button: ⏭️
:ng_button: 🆖
:night_with_stars: 🌃
:nine_oclock: 🕘
:nine-thirty: 🕤
:ninja: ✖
:no_bicycles: 🚳
:no_entry_sign: 🚫
:no_good: 🙅
:no_littering: 🚯
:no_mobile_phones: 📵
:no_mouth: ✖
:non-potable_water: 🚱
:no_one_under_eighteen: 🔞
:no_pedestrians: 🚷
:nose: 👃
:no_smoking: 🚭
:no_smoking: 🚭
:notebook: 📓
:notebook_with_decorative_cover: 📔
:notes: 🎶
:nut_and_bolt: 🔩
:o_button_(blood_type): 🅾️
:octopus: 🐙
:oden: 🍢
:office_building: 🏢
:ogre: 👹
:ok_button: 🆗
:ok_hand: 👌
:ok_hand: ✖
:old_man: 👴
:old_woman: 👵
:on!_arrow: 🔛
:oncoming_automobile: 🚘
:oncoming_bus: 🚍
:oncoming_fist: 👊
:oncoming_police_car: 🚔
:oncoming_taxi: 🚖
:one_oclock: 🕐
:one-thirty: 🕜
:oops: ✖️
:open_book: 📖
:open_file_folder: 📂
:open_hands: 👐
:open_mailbox_with_lowered_flag: 📭
:open_mailbox_with_raised_flag: 📬
:open_mouth: 😮
:ophiuchus: ⛎
:optical_disk: 💿
:orange_book: 📙
:outbox_tray: 📤
:ox: 🐂
:package: 📦
:page_facing_up: 📄
:pager: 📟
:page_with_curl: 📃
:palm_tree: 🌴
:panda: 🐼
:paperclip: 📎
:parachute: ✖️
:parrot: ✖
:partying_face: ✖
:party_popper: 🎉
:passport_control: 🛂
:paw_prints: 🐾
:peach: 🍑
:pear: 🍐
:penguin: 🐧
:pensive: 😔
:pensive_face: 😔
:pentagram: ⛤
:people_hugging: ✖️
:people_with_bunny_ears: 👯
:performing_arts: 🎭
:persevering_face: 😣
:person_biking: 🚴
:person:_blond_hair: 👱
:person_bowing: 🙇
:person_cartwheeling: 🤸
:person_facepalming: 🤦
:person_fencing: 🤺
:person_frowning: 🙍
:person_gesturing_no: 🙅
:person_gesturing_ok: 🙆
:person_getting_haircut: 💇
:person_getting_massage: 💆
:person_in_lotus_position: 🧘
:person_mountain_biking: 🚵
:person_pouting: 🙎
:person_raising_hand: 🙋
:person_rowing_boat: 🚣
:person_running: 🏃
:person_shrugging: 🤷
:person_surfing: 🏄
:person_swimming: 🏊
:person_taking_bath: 🛀
:person_tipping_hand: 💁
:person_walking: 🚶
:person_wearing_turban: 👳
:person_with_skullcap: 👲
:person_with_veil: 👰
:petri_dish: 🧫
:pig: 🐖
:pig_face: 🐷
:pig_nose: 🐽
:pile_of_poo: 💩
:pill: 💊
:pineapple: 🍍
:pine_decoration: 🎍
:ping_pong: 🏓
:pirate_flag: 🏴‍☠
:pizza: 🍕
:planet-orange-purple-ring: ✖
:play_or_pause_button: ⏯️
:pleading_face: ✖
:plus: ➕
:point_left: 👈
:point_right: 👉
:point_up: ☝️
:police_car: 🚓
:police_car_light: 🚨
:police_officer: 👮
:poodle: 🐩
:pool_8_ball: 🎱
:poop: 💩
:popcorn: 🍿
:postal_horn: 📯
:postbox: 📮
:post_office: 🏤
:potable_water: 🚰
:potato: 🥔
:pot_of_food: 🍲
:poultry_leg: 🍗
:pound_banknote: 💷
:pouting_cat: 😾
:pouting_face: 😡
:pray: 🙏
:princess: 👸
:prohibited: 🚫
:punch: 👊
:purple_heart: 💜
:purse: 👛
:pushpin: 📌
:question: ❓
:rabbit: 🐇
:rabbit_face: 🐰
:racehorse: 🐎
:radio: 📻
:radioactive: ☢️
:radioactive_sign: ☢️
:radio_button: 🔘
:rage: 😡
:railway_car: 🚃
:rainbow: 🌈
:rainbow_flag: 🏳️‍🌈
:raised_fist: ✊
:raised_hand: ✋
:raised_hands: ✋
:raised_hand_with_fingers_splayed: 🖐️
:raised_hand_with_part_between_middle_and_ring_fingers: 🖖
:raising_hands: 🙌
:ram: 🐏
:rat: 🐀
:recycling_symbol: ✖
:red_apple: 🍎
:red_circle: 🔴
:red_exclamation_mark: ❗
:red_heart: ❤
:red_paper_lantern: 🏮
:red_question_mark: ❓
:red_triangle_pointed_down: 🔻
:red_triangle_pointed_up: 🔺
:regional_indicator_symbol_letter_a: 🇦
:regional_indicator_symbol_letter_b: 🇧
:regional_indicator_symbol_letter_c: 🇨
:regional_indicator_symbol_letter_d: 🇩
:regional_indicator_symbol_letter_e: 🇪
:regional_indicator_symbol_letter_f: 🇫
:regional_indicator_symbol_letter_g: 🇬
:regional_indicator_symbol_letter_h: 🇭
:regional_indicator_symbol_letter_i: 🇮
:regional_indicator_symbol_letter_j: 🇯
:regional_indicator_symbol_letter_k: 🇰
:regional_indicator_symbol_letter_l: 🇱
:regional_indicator_symbol_letter_m: 🇲
:regional_indicator_symbol_letter_n: 🇳
:regional_indicator_symbol_letter_o: 🇴
:regional_indicator_symbol_letter_p: 🇵
:regional_indicator_symbol_letter_q: 🇶
:regional_indicator_symbol_letter_r: 🇷
:regional_indicator_symbol_letter_s: 🇸
:regional_indicator_symbol_letter_t: 🇹
:regional_indicator_symbol_letter_u: 🇺
:regional_indicator_symbol_letter_v: 🇻
:regional_indicator_symbol_letter_w: 🇼
:regional_indicator_symbol_letter_x: 🇽
:regional_indicator_symbol_letter_y: 🇾
:regional_indicator_symbol_letter_z: 🇿
:relaxed: ☺️
:relieved_face: 😌
:repeat_button: 🔁
:repeat_single_button: 🔂
:restroom: 🚻
:revolving_hearts: 💞
:ribbon: 🎀
:rice_ball: 🍙
:rice_cracker: 🍘
:rice_scene: 🍚
:right_arrow: ➡️
:right_facing_fist: 🤜
:right-handed_interlaced_pentagram: ⛥
:ring: 💍
:roasted_sweet_potato: 🍠
:robot: 🤖
:rock: ✖
:rocket: 🚀
:roller_coaster: 🎢
:rolling_on_the_floor_laughing: 🤣
:roll_of_paper: ✖
:rooster: 🐓
:rose: 🌹
:rotating_light: 🚨
:round_pushpin: 📍
:rugby_football: 🏉
:runner: 🏃
:running: 🏃
:running_shirt: 🎽
:running_shoe: 👟
:sad_but_relieved_face: 😥
:sailboat: ⛵
:sake: 🍶
:santa: 🎅
:santa_claus: 🎅
:satellite_antenna: 📡
:satisfied: ✖
:saxophone: 🎷
:school: 🏫
:school_satchel: 🎒
:scissors: ✂
:scream: 😱
:scroll: 📜
:seat: 💺
:seedling: 🌱
:see_no_evil: 🙈
:see-no-evil_monkey: 🙈
:see_no_evil_monkey: 🙈
:selfie: 🤳
:seven_oclock: 🕖
:seven-thirty: 🕢
:shaved_ice: 🍧
:sheaf_of_rice: 🌾
:ship: 🚢
:shoe: 👞
:shooting_star: 🌠
:shortcake: 🍰
:shower: 🚿
:shuffle_tracks_button: 🔀
:shushing_face: 🤫
:sign_of_the_horns: 🤘
:six_oclock: 🕕
:six-thirty: 🕡
:skis: 🎿
:skull: 💀
:skunk: ✖
:sleeping: 😴
:sleeping_face: 😴
:sleepy: 😪
:sleepy_face: 😪
:slightly_frowning_face: 🙁
:slightly_smiling_face: 🙂
:slot_machine: 🎰
:small_airplane: 🛩
:small_blue_diamond: 🔹
:small_orange_diamond: 🔸
:smile: 🙂
:smiley: 😍
:smiling_cat_with_heart-eyes: 😻
:smiling_cat_with_heart_eyes: 😻
:smiling_face: 😍
:smiling_face_with_halo: 😇
:smiling_face_with_heart-eyes: 😍
:smiling_face_with_heart_eyes: 😍
:smiling_face_with_hearts: 😍
:smiling_face_with_horns: 😈
:smiling_face_with_smiling_eyes: 😊
:smiling_face_with_sunglasses: 😎
:smiling_face_with_tear: ✖
:smiling_imp: 😍
:smirk: 😏
:smirking_face: 😏
:smoking: 🚬
:snail: 🐌
:snake: 🐍
:sneezing_face: 🤧
:snowboarder: 🏂
:soap: ✖
:sob: 😭
:soccer: ⚽
:soccer_ball: ⚽
:socialdist: ✖️
:softball: ⚽
:soft_ice_cream: 🍦
:soon_arrow: 🔜
:sos_button: 🆘
:space_invader: 👾
:spaghetti: 🍝
:sparkler: 🎇
:sparkles: ✨
:sparkling_heart: 💖
:speaker_high_volume: 🔊
:speaker_low_volume: 🔈
:speaker_medium_volume: 🔉
:speaking_head: 🗣
:speaking_head_in_silhouette: 🗣️
:speak_no_evil: 🙊
:speak-no-evil_monkey: 🙊
:speak_no_evil_monkey: 🙊
:speech_balloon: 💬
:speedboat: 🚤
:spiral_shell: 🐚
:sports_medal: ✖
:sport_utility_vehicle: 🚙
:spouting_whale: 🐳
:squinting_face_with_tongue: 😝
:star_struck: 🤩
:station: 🚉
:statue_of_liberty: 🗽
:steaming_bowl: 🍜
:stop_sign: 🛑
:stopwatch: ⏱️
:straight_ruler: 📏
:strawberry: 🍓
:stuck_out_tongue_winking_eye: 😝
:studio_microphone: 🎙️
:sun: ☀
:sunflower: 🌻
:sunglasses: 🕶️
:sunny: ☀️
:sunrise: 🌅
:sunrise_over_mountains: 🌄
:sunset: 🌇
:sun_with_face: 🌞
:sushi: 🍣
:suspension_railway: 🚟
:sweat_droplets: 💦
:sweat_smile: 😅
:syringe: 💉
:table_tennis_paddle_and_ball: 🏓
:tanabata_tree: 🎋
:tangerine: 🍊
:taxi: 🚕
:teacup_without_handle: 🍵
:tear-off_calendar: 📆
:telephone_receiver: 📞
:telescope: 🔭
:television: 📺
:tennis: 🎾
:ten_oclock: 🕙
:ten-thirty: 🕥
:test_tube: 🧪
:thermometer: 🌡
:thinking: 🤔
:thinking_face: 🤔
:thought_balloon: 💭
:three_oclock: 🕒
:three-thirty: 🕞
:thumbs_down: 👎
:thumbs_up: 👍
:thumbsup: 👍
:ticket: 🎫
:tiger: 🐅
:tiger_face: 🐯
:timer_clock: ⏲️
:tired_face: 😫
:toilet: 🚽
:tokyo_tower: 🗼
:tomato: 🍅
:tongue: 👅
:top_arrow: 🔝
:top_hat: 🎩
:tophat: 🎩
:tractor: 🚜
:train: 🚆
:train2: 🚆
:tram: 🚊
:tram_car: 🚋
:transgender_symbol: ⚧️
:triangular_flag: 🚩
:triangular_ruler: 📐
:trident: 🔱
:trident_emblem: 🔱
:trolleybus: 🚎
:trophy: 🏆
:tropical_drink: 🍹
:tropical_fish: 🐠
:truck: 🚚
:trumpet: 🎺
:t-shirt: 👕
:tulip: 🌷
:tumbler_glass: 🥃
:turkey: 🦃
:turtle: 🐢
:tv: 📺
:twelve_oclock: 🕛
:twelve-thirty: 🕧
:two_hearts: 💕
:two-hump_camel: 🐫
:two_oclock: 🕑
:two-thirty: 🕝
:umbrella: ☂️
:umbrella_on_ground: ⛱️
:umbrella_with_rain_drops: ☔
:unamused: 😒
:unamused_face: 😒
:unicorn: 🦄
:unicorn_face: 🦄
:unlocked: 🔓
:up!_button: 🆙
:upside_down_face: 🙃
:upwards_button: 🔼
:v: ✌
:vertical_traffic_light: 🚦
:vhs: 📼
:vibration_mode: 📳
:victory_hand: ✌
:video_camera: 📹
:videocassette: 📼
:video_game: 🎮
:violin: 🎻
:volcano: 🌋
:vs_button: 🆚
:vulcan_salute: 🖖
:waning_crescent_moon: 🌘
:waning_gibbous_moon: 🌖
:warning: ⚠
:washhands: ✖
:water_buffalo: 🐃
:water_closet: 🚾
:watermelon: 🍉
:water_pistol: 🔫
:water_wave: 🌊
:wave: 🌊
:waving_hand: 👋
:waving_white_flag: 🏳️
:waxing_crescent_moon: 🌒
:waxing_gibbous_moon: 🌔
:weary_cat: 🙀
:weary_face: 😩
:wedding: 💒
:whale: 🐋
:wheelchair: ♿
:wheelchair_symbol: ♿
:white_exclamation_mark: ❕
:white_flag: 🏳️
:white_flower: 💮
:white_question_mark: ❔
:white_square_button: 🔳
:wilted_flower: 🥀
:wind_chime: 🎐
:wine_glass: 🍷
:wink: 😉
:winking_face: 😉
:winking_face_with_tongue: 😜
:wolf: 🐺
:woman: 👩
:woman_and_man_holding_hands: 👫
:woman_cartwheeling: 🤸‍♀️
:woman_dancing: 💃
:woman_genie: ✖
:woman_in_lotus_position: 🧘‍♀
:woman_raising_hand: 🙋‍♀
:womans_boot: 👢
:womans_clothes: 👚
:womans_hat: 👒
:womans_sandal: 👡
:woman_surfing: 🏄‍
:women_holding_hands: 👭
:womens_room: 🚺
:woozy_face: ✖
:wrapped_gift: 🎁
:wrench: 🔧
:x: ✖
:yawning_face: ✖
:yellow_heart: 💛
:yen_banknote: 💴
:yougotthis: ✖
:yt: ▶️
:yum: 😋
:zany_face: 🤪
:zap: ✖
:zipper_mouth_face: 🤐
:zzz: 😴
:bat: 🦇
:body-green-covering-eyes: 💩
:eyes-purple-crying: 💩
:face-blue-wide-eyes: 💩
:face-fuchsia-tongue-out: 💩
:face-green-smiling: 💩
:face-orange-biting-nails: 💩
:face-orange-frowning: 💩
:face-pink-tears: 💩
:face-purple-sweating: 💩
:face-red-droopy-eyes: 💩
:face-red-heart-shape: 💩
:mango: 💩
:man’s_shoe: 💩
:shamrock: 💩
:teacher: 💩
:trophy-yellow-smiling: 💩
:virtualhug: 💩
EOF
fi
}
